{% set name = "multifutures" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multifutures-{{ version }}.tar.gz
  sha256: bd3745c42c9424b8c7001d0a9c358df217f29531a5517532cdcba3b4e5590beb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9
    - exceptiongroup
    - limits
    - tqdm
  run_constrained:
    - loky *
    - psutil *

test:
  imports:
    - multifutures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmav99/multifutures.git
  summary: Multiprocessing/multithreading made easy
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmav99
